<?php

namespace Yoda\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByUsernameOrEmail($usernameOremail)
    {
        return $this->createQueryBuilder('u')
            ->andWhere('u.username = :username OR u.email = :email')
            ->setParameter('username', $usernameOremail)
            ->setParameter('email', $usernameOremail)
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
