# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Yoda\UserBundle\Entity\User: bcrypt
        # Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN:  [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]        

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_database_users:
            entity:
                class: UserBundle:User
#                property: username
    
        # in_memory:
        #    memory: 
        #        users:
        #            user: { password: userpass, roles: ['ROLE_USER'] }
        #            admin: { password: adminpass, roles: ['ROLE_ADMIN'] }


    firewalls:
        secured_area:
            pattern: ^/
            form_login:
                check_path: login_check
                login_path: login_form
            logout:
                path: logout
                target: event
            anonymous: ~        


    access_control:
    # Putting security access control in the controller instead :
#        - { path: ^/new, roles: ROLE_USER }
#        - { path: ^/create, roles: ROLE_USER }