# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        secured_area:
            pattern: ^/
            form_login:
                check_path: _security_check
                login_path: /my-login-url
            logout:
                path: _demo_logout
                target: _demo
            anonymous: ~        


    access_control:
        - { path: ^/new, roles: ROLE_USER }
        - { path: ^/create, roles: ROLE_USER }